# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runBayesPO <- function(beta, delta, lambda, parB, parD, parL, covariates, intensityLink, observabilityLink, areaD, xValues, intensityCovs, observabilityCovs, xIntensityCovs, xObservabilityCovs, burnin, thin, iter, threads, verbose) {
    .Call(`_bayesPO_runBayesPO`, beta, delta, lambda, parB, parD, parL, covariates, intensityLink, observabilityLink, areaD, xValues, intensityCovs, observabilityCovs, xIntensityCovs, xObservabilityCovs, burnin, thin, iter, threads, verbose)
}

